export enum Policies {
    SUPER_ADMIN = 'SUPERADMIN',
    ORG_ADMIN = "ORGADMIN",
    PROJECT_COLLABRATOR = "PROJECT_COLLABRATOR",
    PROJECT_OWNER = "PROJECT_OWNER",
    PROJECT_DEVELOPER = "PROJECT_DEVELOPER",
    REVIEWER = " REVIEWER",
    EDITOR = "EDITOR"
}